Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/models/base.py
from teamapp.extensions import db

class BaseModel(db.Model):

    __abstract__=True
    def create(self, commit=True):
        db.session.add(self)
        if commit:
            db.session.commit()
    
    def save(self):
        db.session.commit()

Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/models/question.py
from teamapp.extensions import db
from .base import BaseModel


class Question(BaseModel):
    id=db.Column(db.Integer, primary_key=True)
    question=db.Column(db.Text)
    answer=db.Column(db.Text)
    asked_by_id=db.Column(db.Integer, db.ForeignKey('user.id'))
    mentor_id=db.Column(db.Integer, db.ForeignKey('user.id'))

Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/models/user.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash
from teamapp.extensions import db
from .base import BaseModel


class User(UserMixin, BaseModel):
    id=db.Column(db.Integer, primary_key=True, unique=True)
    name=db.Column(db.String(50))
    password=db.Column(db.String(280))
    senior=db.Column(db.Boolean)
    junior=db.Column(db.Boolean)
    intern=db.Column(db.Boolean)
    admin=db.Column(db.Boolean)

    questions_asked=db.relationship('Question', foreign_keys='Question.asked_by_id', backref='asker', lazy=True)
    answers_expected=db.relationship('Question', foreign_keys='Question.mentor_id', backref='mentor', lazy=True)

    @property
    def unhashed_password(self):
        raise AttributeError('Unhashed password!')
    
    @unhashed_password.setter
    def unhashed_password(self, unhashed_password):
        self.password=generate_password_hash(unhashed_password)

Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/views/main/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, RadioField
from wtforms.validators import InputRequired
from teamapp.models.user import User
from flask import request
from wtforms_sqlalchemy.fields import QuerySelectField
from sqlalchemy import or_
from teamapp.extensions import db


class AnswerForm(FlaskForm):
    textarea=TextAreaField(validators=[InputRequired()])


def user_query():
    return User.query.filter(db.or_(User.senior==True, User.junior==True))


class AskForm(FlaskForm):
    textarea=TextAreaField(validators=[InputRequired()])
    options=QuerySelectField(query_factory=user_query, allow_blank=False, get_label='name')


class RadioForm(FlaskForm):
    radio=RadioField('Radios', choices=[('senior', 'Senior'), ('junior', 'Junior'), ('intern', 'Intern')])

Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/__init__.py
from flask import Flask
from .commands import init_db
from .extensions import db, login_manager, migrate
from .models.user import User
from .views.auth.routes import auth
from .views.main.routes import main
from .config import Config

BLUEPRINTS=[main, auth]
COMMANDS=[init_db]

def create_app():
    app=Flask(__name__)
    app.config.from_object(Config)
    register_extensions(app)
    register_blueprints(app)
    register_commands(app)

    login_manager.login_view='auth.login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)


    return app


def register_blueprints(app):
    for blueprint in BLUEPRINTS:
        app.register_blueprint(blueprint)

def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

def register_commands(app):
    for command in COMMANDS:
        app.cli.add_command(command)

Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/views/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import or_, desc
from teamapp.models.question import Question
from teamapp.models.user import User

from .forms import AnswerForm, AskForm, RadioForm

main=Blueprint('main', __name__, template_folder="templates")

@main.route('/')
def index():
    questions=Question.query.filter(Question.answer!= None).order_by(desc(Question.id)).all()
    lst=[]
    act=0
    for i in questions:
        lst.append(i.id)
    
    if len(lst)>=1:
        act=max(lst)

    context={
        'questions':questions, 
        'act': act
    }

    return render_template('main/home.html', **context)




@main.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    form=AskForm()
    if form.validate_on_submit():
        question=request.form['textarea']
        mentor=request.form['options']
        question=Question(question=question, mentor_id=mentor, asked_by_id=current_user.id)
            
        question.create()
        print('submitted')
        return redirect(url_for('main.index'))
    return render_template('main/ask.html', form=form)



@main.route('/unanswered')
@login_required
def unanswered():
    unanswered_questions=Question.query.filter_by(mentor_id=current_user.id).filter(Question.answer==None).order_by(desc(Question.id)).all()
    lst=[]
    act=0
    for i in unanswered_questions:
        lst.append(i.id)
    
    if len(lst)>=1:
          act=max(lst)
   

    context={
        'unanswered_questions': unanswered_questions, 
        'act': act
    }

    return render_template('main/unanswered.html', **context)


@main.route('/answer/<int:question_id>', methods=['GET', 'POST'])
@login_required
def answer(question_id):
    form=AnswerForm()
    question=Question.query.get_or_404(question_id)

    if request.method=='POST':
        question.answer=request.form['textarea']
        question.save()


        return redirect(url_for('main.unanswered'))

    context={
        'question': question
    }

    return render_template('main/answer.html', **context, form=form)




@main.route('/question/<int:question_id>')
def question(question_id):
    question=Question.query.get_or_404(question_id)

    context={
        'question': question
    }

    return render_template('main/question.html', **context)



@main.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    form=RadioForm
    users=User.query.filter_by(admin=False).all()

    context={
        'users': users
    }


    return render_template('main/users.html', **context, form=form)



    
@main.route('/assign', methods=['GET', 'POST'])
@login_required
def assign():
    if not current_user.admin:
        return redirect(url_for('main.index'))
    status=None
    form_status=None
    users=User.query.filter_by(admin=False).all()
    for user in users:
        if user.senior==1:
            status='0'
        elif user.junior==1:
            status='1'
        elif user.intern==1:
            status='2'
        form_status=request.form.get(str(user.id))
        if status!=form_status:
            status=form_status
            if status=='0':
                user.senior=1 
                user.junior=0
                user.intern=0
            
            elif status=='1':
                user.senior=0
                user.junior=1
                user.intern=0
            elif status=='2':
                user.senior=0
                user.junior=0
                user.intern=1
        user.save()
    return redirect(url_for('main.users'))
        



 

Chapter09_Structuring/Projects/2023/mariam_razmadze/teamapp/templates/macro.html
{%macro show_links( current_user )%}
<ul>
  <li>
    <a href="{{url_for('main.index')}}"><i class="fas fa-home"></i>Home</a>
  </li>
  {% if not current_user.is_authenticated %}
  <li>
    <a href="{{url_for('auth.login')}}"
      ><i class="fa-solid fa-right-to-bracket"></i> Login</a
    >
  </li>
  <li>
    <a href="{{url_for('auth.register')}}"
      ><i class="fa-solid fa-user-plus"></i> Register</a
    >
  </li>
  {% endif %} {% if current_user.is_authenticated and current_user.admin==0 and
  current_user.senior==0 %}
  <li>
    <a href="{{url_for('main.ask')}}"
      ><i class="fa-solid fa-question"></i> Ask Questions</a
    >
  </li>
  {% endif %} {% if current_user.is_authenticated and current_user.senior==1 or
  current_user.junior==1%}
  <li>
    <a href="{{url_for('main.unanswered')}}"
      ><i class="fa-brands fa-replyd"></i> Answer
    </a>
  </li>
  {% endif %} {% if current_user.is_authenticated and current_user.admin==1 %}
  <li>
    <a href="{{url_for('main.users')}}"
      ><i class="fa-solid fa-users-gear"></i> User Setup</a
    >
  </li>
  {% endif %} {% if current_user.is_authenticated %}
  <li>
    <a href="{{url_for('auth.logout')}}"
      ><i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a
    >
  </li>
  {% endif %}
</ul>

{%endmacro%}

{%macro renderfield(field)%}
<div>
  <div>
    {{field(**kwargs)}}
    <label for="{{field.name}}" class_="form-control label"
      >{{field.label.text}}</label
    >
    </div>
    <ul>
      {% for error in field.errors%}
      <li style="color: #8b0f32">{{error}}</li>
      {%endfor%}
    </ul>
    </div>
    {%endmacro%}
  </div>
</div>

{%macro nolabel(field)%}
<div>
  <div>
    {{field(**kwargs)}}
    </div>
    <ul>
      {% for error in field.errors%}
      <li style="color: #8b0f32">{{error}}</li>
      {%endfor%}
    </ul>
    </div>
    {%endmacro%}
  </div>
</div>

{%macro render_radio(field)%}
<div class="form-check form-check-inline">
  {{field}}
  {{field.label.text}}
  <label class="form-check-label"></label>
</div>
<div class="form-check form-check-inline">
  {{field}}
  {{field.label.text}}
  <label class="form-check-label"></label>
</div>
<div class="form-check form-check-inline">
  {{field}}
  {{field.label.text}}
  <label class="form-check-label"></label></a>
</div>
<div>
  <div>
   
    </div>
    <ul>
      {% for error in field.errors%}
      <li style="color: #8b0f32">{{error}}</li>
      {%endfor%}
    </ul>
    </div>
    {%endmacro%}
  </div>
</div>