Chapter9_Structuring/Projects/mariam_kavtaradze/source/user/models.py
from source.models.base_model import BaseModel
from source import db


class User(BaseModel):
    __tablename__ = 'user'
    __table_args__ = {'extend_existing': True}

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(24))
    email = db.Column(db.String(48))
    password = db.Column(db.String(48))
    experience = db.Column(db.String(24))
    account_type = db.Column(db.String(24))

Chapter9_Structuring/Projects/mariam_kavtaradze/source/user/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, EmailField, PasswordField, SubmitField, RadioField, SelectField, IntegerField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class BaseForm(FlaskForm):
    username = StringField(label="Username", validators=[DataRequired(), Length(min=4, max=24)])
    email = EmailField(label="Email", validators=[Email()])
    password = PasswordField(label="Password")
    confirm_password = PasswordField(label="Confirm Password", validators=[EqualTo('password', message="Passwords don't match")])
    experience = RadioField(choices=[("beginner", "Beginner"), ("some experience", "Some Experience"), ("veteran", "Veteran")])
    account_type = SelectField(choices=[(1, "User"), (2, "Creator"), (3, "Venue")])
    submit = SubmitField()


class GetForm(FlaskForm):
    id = IntegerField('User ID')
    submit = SubmitField("Submit")

Chapter9_Structuring/Projects/mariam_kavtaradze/source/__init__.py
from flask import Flask
from source.extensions import db, migrate


def create_app(config_file='config.py'):
    app = Flask(__name__)
    app.config.from_pyfile(config_file)
    register_extensions(app)
    register_blueprints(app)

    return app


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db)


def register_blueprints(app):
    from source.user.views import user_blueprint
    app.register_blueprint(user_blueprint, url_prefix='/user')
    from source.front.views import base_blueprint
    app.register_blueprint(base_blueprint)

Chapter9_Structuring/Projects/mariam_kavtaradze/source/user/views.py
from flask import Blueprint, render_template, url_for, redirect
from source.user.forms import BaseForm, GetForm
from source.user.models import User

user_blueprint = Blueprint('user',
                           __name__,
                           template_folder='templates/users')


@user_blueprint.route('/create', methods=['GET', 'POST'])
def create():
    form = BaseForm()

    if form.validate_on_submit():
        username = form.username.data
        email = form.email.data
        password = form.password.data
        experience = form.experience.data
        account_type = form.account_type.data
        user = User()
        user.create(username=username,
                    email=email,
                    password=password,
                    experience=experience,
                    account_type=account_type,
                    commit=True)
        return redirect(url_for('user.read_all'))
    return render_template("create.html", form=form)


@user_blueprint.route('/read_all', methods=['GET'])
def read_all():
    all_users = User.read_all()
    return render_template('read_all.html', all_users=all_users)


@user_blueprint.route('/read_one', methods=['GET', 'POST'])
def read_one():
    form = GetForm()
    if form.validate_on_submit():
        user_id = form.id.data
        user = User.read_one(user_id)
        return render_template('read_one.html', user=user)
    return render_template('get_user.html', form=form)


@user_blueprint.route('/update', methods=['GET', 'POST'])
def update():
    get_form = GetForm()
    all_users = User.read_all()
    if get_form.validate_on_submit():

        user = User.read_one(get_form.id.data)
        form = BaseForm()
        if form.validate_on_submit():
            username = form.username.data
            email = form.email.data
            experience = form.experience.data
            account_type = form.account_type.data
            user.update(username=username,
                        email=email,
                        experience=experience,
                        account_type=account_type,
                        commit=True)
            return redirect(url_for('user.read_all'))
        return render_template('update.html', user=user, form=form)
    return render_template('get_user.html', all_users=all_users, form=get_form)


@user_blueprint.route('/delete', methods=['GET', 'POST'])
def delete():
    form = GetForm()
    all_users = User.read_all()
    if form.validate_on_submit():
        user_id = form.id.data
        user = User.query.get(user_id)
        user.delete()
        return redirect(url_for('user.read_all'))
    return render_template('get_user.html', all_users=all_users, form=form)

Chapter9_Structuring/Projects/mariam_kavtaradze/source/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
    <title>randomtit</title>
</head>
<div class="flex-parent jc-position">
    <button class="button" onclick=" window.open('https://github.com/MxKavt','_blank')"> HIT ME UP ON GITHUB_</button>
</div>
<body>
<div class="headerText">
    <!-- Headers -->
    <div class="headerBorder">
    <h1>POISON BAR</h1>
    </div>
</div>
<div class="mainText">
    <div class="mainBorder">
        <div class="titlesText">
            <h3>YOUR SPACE FOR CREATING, SHARING AND RESEARCHING SPECIALTY BLENDS AND VENUES</h3>
        </div>
        <div class="drop_options">
            <button class="options_btn" >Vibe Check</button>
            <div class="options_content">
            <a class="options" href='#'>Manually</a>
            <a class="options" href="#">Automatically</a>
            </div>
        </div>
        <div class="drop_options">
            <button class="options_btn">Enter Your Space</button>
            <div class="options_content">
            <a class="options" href="#">Login</a>
            <a class="options" href={{ url_for('user.create') }}>Register</a>
            </div>
        </div>
        <div class="drop_options">
            <button class="options_btn">Actions</button>
            <div class="options_content">
            <a class="options" href={{ url_for('user.read_all') }}>List Users</a>
            <a class="options" href={{ url_for('user.read_one') }}>Get One User</a>
            <a class="options" href={{ url_for('user.update') }}>Update Users</a>
            <a class="options" href={{ url_for('user.delete') }}>Delete Users</a>
            </div>
        </div>
    <h3 style="text-align: left">Goals</h3>
        <ol style="text-align: left">
            <li>Popularising the field of mixology</li>
            <li>Connecting creators with potential employers</li>
            <li>Simplified search for venues depending on the user preferences</li>
            <li>Protection of intellectual property for creators</li>
        </ol>
    <h3>Tools used/to be used</h3>
        * HTML * CSS
        * Flask-RESTful
        * SQLite
        * json
    </div>
</div>
<br>
<div class="randBox">
    <p>
        The sky above the port was the color of television, tuned to a dead channel.
    </p>
</div>
<div class="flex-parent jc-position">
    <a class="button" href='#'>TAKE A RIDE ON A CAROUSEL_</a>
</div>
</body>
</html>