Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash

from .extensions import db

class User(UserMixin, db.Model):
    id=db.Column(db.Integer, primary_key=True)
    name=db.Column(db.String(50))
    password=db.Column(db.String(80))
    senior=db.Column(db.Boolean)
    junior=db.Column(db.Boolean)
    intern=db.Column(db.Boolean)
    admin=db.Column(db.Boolean)

    questions_asked=db.relationship('Question', foreign_keys='Question.asked_by_id', backref='asker', lazy=True)
    answers_expected=db.relationship('Question', foreign_keys='Question.mentor_id', backref='mentor', lazy=True)

    @property
    def unhashed_password(self):
        raise AttributeError('Unhashed password!')
    
    @unhashed_password.setter
    def unhashed_password(self, unhashed_password):
        self.password=generate_password_hash(unhashed_password)



class Question(db.Model):
    id=db.Column(db.Integer, primary_key=True)
    question=db.Column(db.Text)
    answer=db.Column(db.Text)
    asked_by_id=db.Column(db.Integer, db.ForeignKey('user.id'))
    mentor_id=db.Column(db.Integer, db.ForeignKey('user.id'))

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/__init__.py
from flask import Flask
from .commands import create_tables
from .extensions import db, login_manager
from .models import User
from .routes.auth import auth
from .routes.main import main

def create_app(config_file='settings.py'):
    app=Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)
    login_manager.init_app(app)

    login_manager.login_view='auth.login'

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    app.register_blueprint(main)
    app.register_blueprint(auth)

    app.cli.add_command(create_tables)

    return app

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_user, logout_user
from ..import login_manager
from werkzeug.security import check_password_hash


from ..extensions import db
from ..models import User

auth=Blueprint('auth', __name__)

# @login_manager.user_loader
@auth.route('/register', methods=['GET', 'POST'])
def register():
    names=[]
    users=User.query.all()
    for user in users:
        names.append(user.name)
    error_message=''
    if request.method=='POST':
        name=request.form['name']
        unhashed_password=request.form['password']
        user=User(name=name, unhashed_password=unhashed_password, intern=True, junior=False, senior=False, admin=False)
        error_message=""
        if user.name in names:
            error_message="User with that username already exists, sorry ❕"
            # return redirect(url_for('auth.login'))
        
        if not error_message:
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))

            
    return render_template('register.html',  error_message=error_message)

@login_manager.user_loader
@auth.route('/login', methods=['GET', 'POST'])
def login():
    error_message=''
    if request.method=='POST':
        name=request.form['name']
        password=request.form['password']

        user=User.query.filter_by(name=name).first()

        error_message=""

        if not user or not check_password_hash(user.password, password):
            error_message="Your password is incorrect or this account doesn't exist ❕"
        
        if not error_message:
            login_user(user)
            return redirect(url_for('main.index'))
    

    return render_template('login.html', error_message=error_message)


@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/routes/main.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import current_user, login_required
from sqlalchemy import or_, desc

from ..extensions import db
from ..models import Question, User

main=Blueprint('main', __name__)

@main.route('/')
def index():
    questions=Question.query.filter(Question.answer!= None).order_by(desc(Question.id)).all()
    lst=[]
    act=0
    for i in questions:
        lst.append(i.id)
    
    if len(lst)>=1:
        act=max(lst)

    context={
        'questions':questions, 
        'act': act
    }

    return render_template('home.html', **context)


@main.route('/ask', methods=['GET', 'POST'])
@login_required
def ask():
    if request.method=='POST':
        question=request.form['question']
        mentor=request.form['mentor']

        question=Question(question=question, mentor_id=mentor, asked_by_id=current_user.id)


        db.session.add(question)
        db.session.commit()


        return redirect(url_for('main.ask'))
    mentors=User.query.filter(or_(User.senior==True, User.junior==True)).all()

    context={
        "mentors": mentors
    }

    return render_template('ask.html', **context)


@main.route('/unanswered')
@login_required
def unanswered():
    # if not current_user.senior or not current_user.junior:
    #     return redirect(url_for('main.index'))
    unanswered_questions=Question.query.filter_by(mentor_id=current_user.id).filter(Question.answer==None).order_by(desc(Question.id)).all()
    lst=[]
    act=0
    for i in unanswered_questions:
        lst.append(i.id)
    
    if len(lst)>=1:
          act=max(lst)
   

    context={
        'unanswered_questions': unanswered_questions, 
        'act': act
    }

    return render_template('unanswered.html', **context)


@main.route('/answer/<int:question_id>', methods=['GET', 'POST'])
@login_required
def answer(question_id):
    # if not current_user.senior or not current_user.junior:
    #     return redirect(url_for('main.index'))
    question=Question.query.get_or_404(question_id)

    if request.method=='POST':
        question.answer=request.form['answer']
        db.session.commit()

        return redirect(url_for('main.unanswered'))

    context={
        'question': question
    }

    return render_template('answer.html', **context)




@main.route('/question/<int:question_id>')
def question(question_id):
    question=Question.query.get_or_404(question_id)

    context={
        'question': question
    }

    return render_template('question.html', **context)


@main.route('/users', methods=['GET', 'POST'])
@login_required
def users():
    users=User.query.filter_by(admin=False).all()

    context={
        'users': users
    }


    return render_template('users.html', **context)



    
@main.route('/assign', methods=['GET', 'POST'])
@login_required
def assign():
    if not current_user.admin:
        return redirect(url_for('main.index'))
    status=None
    form_status=None
    users=User.query.filter_by(admin=False).all()
    for user in users:
        if user.senior==1:
            status='0'
        elif user.junior==1:
            status='1'
        elif user.intern==1:
            status='2'
        form_status=request.form.get(str(user.id))
        if status!=form_status:
            status=form_status
            if status=='0':
                user.senior=1 
                user.junior=0
                user.intern=0
            
            elif status=='1':
                user.senior=0
                user.junior=1
                user.intern=0
                db.session.commit()
            elif status=='2':
                user.senior=0
                user.junior=0
                user.intern=1
        db.session.commit()
    return redirect(url_for('main.users'))
        



 

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/answer.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | ANSWER</title>
{% endblock%}

{% block body %}
<div class='ask'>
  <div class="wrapper">
    <form action="{{url_for('main.answer', question_id=question.id)}}" method="POST">
      <fieldset>
        <h1 class='ans'>{{question.question}}</h1>
        <textarea
        placeholder="Type your answer here..."
        rows="3"
        name="answer"
        required
      ></textarea>
      <button type="submit" class="ask-btn">Submit your answer</button>
    </fieldset>
  </form>
</div>
</div>
</div>{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/ask.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | ASK</title>
{% endblock%} {% block body %}
<div class='ask'>
<div class="wrapper">
  <form action="{{url_for('main.ask')}}" method="POST">
    <fieldset>
      <h1>What's your question?</h1>
      <textarea
        placeholder="Type your question here..."
        rows="3"
        name="question"
        required
      ></textarea>

      <select class="form-select" name="mentor" required>
        <option selected disabled value="" >
          Choose who the question is inteded for
        </option>
        {% for mentor in mentors %}
        <option value="{{ mentor.id}}">{{mentor.name}}</option>
        {%endfor%}
      </select>

      <button type="submit" class="ask-btn">Submit Your Question</button>
    </fieldset>
  </form>
</div>
</div>
</div>{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/b.html
{%from "macro.html" import show_links%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {%block head%}{%endblock%}

   <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  

    <link
      href="{{ url_for('static', filename='main.css') }}"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

  <body>
    <div class="container-fluid">
      <div class="circle-container">
        <div class="circle">
          <button id="close">
            <i class="fas fa-times"></i>
          </button>
          <button id="open">
            <i class="fas fa-bars"></i>
          </button>
        </div>
      </div>

   {%block body%} {%endblock%}

    <nav>
      <ul>
        <li></li>
      
        <li>
          <a href="{{url_for('auth.register')}}"
            ><i class="fa-solid fa-right-to-bracket"></i> Login</a
          >
        </li>
        <li>
          <a href="{{url_for('auth.register')}}"
            ><i class="fa-solid fa-user-plus"></i> Register</a
          >
        </li>
      
        <li>
          <a href="{{url_for('main.ask')}}"
            ><i class="fa-solid fa-question"></i> Question</a
          >
        </li>
      
        <li>
          <a href="{{url_for('main.ask')}}"
            ><i class="fa-brands fa-replyd"></i> Answer</a
          >
        </li>
      
        <li>
          <a href="{{url_for('main.ask')}}"
            ><i class="fa-solid fa-users-gear"></i> User Setup</a
          >
        </li>
      </ul>
    </nav>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
  </body>
</html>

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/base.html
{%from "macro.html" import show_links%}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    {%block head%}{%endblock%}

   <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
  

    <link
      href="{{ url_for('static', filename='main.css') }}"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
      integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />
  </head>

  <body>
    <div class="container-fluid">
      <div class="circle-container">
        <div class="circle">
          <button id="close">
            <i class="fas fa-times"></i>
          </button>
          <button id="open">
            <i class="fas fa-bars"></i>
          </button>
        </div>
      </div>

   {%block body%} {%endblock%}

    <nav>
      {{show_links(current_user)}}
    </nav>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
    <script src="{{ url_for('static', filename='script.js') }}"></script>
  </body>
</html>

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/home.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | HOME</title>
{% endblock%} {% block body %}
<div class="unanswered">
  <h1>Answered Questions</h1>
  <div class='scr'>
  <div class="q-container"> 
    {%for question in questions%}
    <div class="q {%if question.id==act%} active{%endif%}">
      <a href="{{url_for('main.question', question_id=question.id)}}">
        <h4 class="q-title">{{question.question}}</h4>
        <p class="q-text {%if question.asker.senior==1%} senior
        {%elif question.asker.junior==1%} junior
        {%elif question.asker.intern==1%} intern {%endif%}"> Asked by: {{question.asker.name}}</p>
        <p class="q-text {%if question.mentor.senior==1%} senior
        {%elif question.mentor.junior==1%} junior{%endif%}"> Answered by: {{question.mentor.name}}</p>
      </a>
      <button  class="q-toggle">
        <i class="fas fa-chevron-down"></i>
        <i class="fas fa-times"></i>
      </button>
    </div>
      {%endfor%}
    </div>
  </div>
</div>
</div>

{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/login.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | LOGIN</title>
{% endblock%}

{% block body %}

<div class="container form-cont">
    <h1>Please Login</h1>
    <form method="POST" action="{{url_for('auth.login')}}">
      <div class="form-control">
        <input
          type="text"
          id="name"
          name="name"
          required
        />
        <label for="name">Name</label>
      </div>
      {% if error_message%}
      <div class='alert alert-danger'>{{error_message}}</div>
      {%endif%}
      <div class="form-control">
        <input
          type="password"
          id="password"
          name="password"
          required
        />
        <label for="password">Password</label>
      </div>
        <button type="submit" class="form-btn">Login</button>
      <p class="text">Don't have an account?<a href="register"> Register</a></p>
    </form>
  </div>
</div>


{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/macro.html
{%macro show_links( current_user )%}
<ul>
  <li>
    <a href="{{url_for('main.index')}}"><i class="fas fa-home"></i>Home</a>
  </li>
  {% if not current_user.is_authenticated %}
  <li>
    <a href="{{url_for('auth.login')}}"
      ><i class="fa-solid fa-right-to-bracket"></i> Login</a
    >
  </li>
  <li>
    <a href="{{url_for('auth.register')}}"
      ><i class="fa-solid fa-user-plus"></i> Register</a
    >
  </li>
  {% endif %} {% if current_user.is_authenticated and current_user.admin==0 and
  current_user.senior==0 %}
  <li>
    <a href="{{url_for('main.ask')}}"
      ><i class="fa-solid fa-question"></i> Ask Questions</a
    >
  </li>
  {% endif %} {% if current_user.is_authenticated and current_user.senior==1 or
  current_user.junior==1%}
  <li>
    <a href="{{url_for('main.unanswered')}}"
      ><i class="fa-brands fa-replyd"></i> Answer
    </a>
  </li>
  {% endif %} {% if current_user.is_authenticated and current_user.admin==1 %}
  <li>
    <a href="{{url_for('main.users')}}"
      ><i class="fa-solid fa-users-gear"></i> User Setup</a
    >
  </li>
  {% endif %} {% if current_user.is_authenticated %}
  <li>
    <a href="{{url_for('auth.logout')}}"
      ><i class="fa-solid fa-arrow-right-from-bracket"></i> Logout</a
    >
  </li>
  {% endif %}
</ul>

{%endmacro%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/question.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | QUESTION</title>
{% endblock%} {% block body %}
<div class="unanswered not">
  <div class='scr'>
  <div class="q-container"> 
    <div class="q active">
        <h4 class="q-title">{{question.question}}</h4>
        <p class="q-text {%if question.asker.senior==1%} senior
        {%elif question.asker.junior==1%} junior
        {%elif question.asker.intern==1%} intern {%endif%}"> Asked by: {{question.asker.name}}</p>
        <p class="q-text"> {{question.answer}}</p>
        <p class="q-text {%if question.mentor.senior==1%} senior
        {%elif question.mentor.junior==1%} junior{%endif%}"> Answered by: {{question.mentor.name}}</p>
      <button  class="q-toggle">
        <i class="fas fa-chevron-down"></i>
        <i class="fas fa-times"></i>
      </button>
    </div>
    </div>
  </div>
</div>
</div>

{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/register.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | REGISTER</title>
{% endblock%}

{% block body %}

<div class="container form-cont">
    <h1>Please Register</h1>
    <form method="POST" action="{{url_for('auth.register')}}">
      <div class="form-control">
        <input
          type="text"
          id="name"
          name="name"
          required
        />
        <label for="name">Name</label>
      </div>
      {% if error_message%}
      <div class='alert alert-danger'>{{error_message}}</div>
      {%endif%}
      <div class="form-control">
        <input
          type="password"
          id="password"
          name="password"
          required
        />
        <label for="password">Password</label>
      </div>
        <button type="submit" class="form-btn">Register</button>
      <p class="text">Already have an account?<a href="login"> Login</a></p>
    </form>
  </div>
</div>


{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/unanswered.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | UNANSWERED</title>
{% endblock%} {% block body %}
<div class="unanswered">
  <h1>Questions For You</h1>
  <div class='scr'>
  <div class="q-container"> 
    {%for question in unanswered_questions%}
    <div class="q {%if question.id==act%} active{%endif%}">
      <a href="{{url_for('main.answer', question_id=question.id)}}">
        <h4 class="q-title">{{question.question}}</h4>
        <p class="q-text {%if question.asker.senior==1%} senior
        {%elif question.asker.junior==1%} junior
        {%elif question.asker.intern==1%} intern {%endif%}"> Asked by: {{question.asker.name}}</p>
      </a>
      <button  class="q-toggle">
        <i class="fas fa-chevron-down"></i>
        <i class="fas fa-times"></i>
      </button>
    </div>
      {%endfor%}
    </div>
  </div>
</div>
</div>

{% endblock%}

Chapter07_Database/Projects/2023/mariam_razmadze/teamapp/templates/users.html
{% extends 'base.html' %} {% block head %}
<title>TEAM-APP | USER STATUS</title>
{% endblock%}

{% block body %}
<h1 class='user'>User Status</h1>
<p class='user'>Click to assign or change the status</p>
<div class="user">
    <table class="table">
      <thead>
        <tr>
          <th scope="col" class='pt-5'>Name</th>
          <th scope="col">Status</th>
        </tr>
      </thead>
    {%for user in users%}
      <tbody>
        <tr> 
          <th scope="row" class="{%if user.senior==1%} senior
          {%elif user.junior==1%} junior
          {%elif user.intern==1%} intern {%endif%}">{{user.name}}</th>
          <td>
            <form method="POST" action="{{url_for('main.assign')}}"> 
              <fieldset id="{}".format({{user.name}})>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name={{user.id}} 
                id="senior" value="0">
                <label class="form-check-label" for="senior">Senior</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name={{user.id}}  id="junior" value="1">
                <label class="form-check-label" for="junior">Junior</label>
              </div>
              <div class="form-check form-check-inline">
                <input class="form-check-input" type="radio" name={{user.id}}  id="intern" value="2">
                <label class="form-check-label" for="intern">Intern</label></a>
              </div>
          </fieldset>
        </td>
      </tr>
  </tbody>
      {%endfor%}
  </table>
</div>
<h6 class='user'>Are you sure you want to save changes?</h6> 
<div class='user b'>
    <button type='submit' class='ub'>Save Changes</button>
</div>
</div>
 
</form>
   

{% endblock%}