Chapter10_User/Projects/2024/Vano_Iniashvili/src/models/__init__.py
from src.models.film import Film

Chapter10_User/Projects/2024/Vano_Iniashvili/src/models/base.py
from src.extensions import db


class BaseModel(db.Model):

    __abstract__ = True

    def create(self, commit=True):
        db.session.add(self)

        if commit:
            self.save()
        else:
            db.session.flush()

    def save(self):
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

Chapter10_User/Projects/2024/Vano_Iniashvili/src/models/film.py
from src.extensions import db
from src.models.base import BaseModel
from src.models.user import User


class Film(BaseModel):
    __tablename__ = "films"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    director = db.Column(db.String)
    genre = db.Column(db.String)
    release_date = db.Column(db.DateTime)
    cover = db.Column(db.String())


class UserFilm(BaseModel):
    __tablename__ = 'users_films'

    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    film_id = db.Column(db.Integer, db.ForeignKey('films.id'))

Chapter10_User/Projects/2024/Vano_Iniashvili/src/models/user.py
from src.extensions import db
from flask_login import UserMixin
from src.models.base import BaseModel
from werkzeug.security import generate_password_hash, check_password_hash


class User(BaseModel, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    _password = db.Column(db.String)
    films = db.relationship("Film", secondary="users_films", backref="users")

    def _get_password(self):
        return self._password

    def _set_password(self, password):
        self._password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    password = db.synonym('_password', descriptor=property(_get_password, _set_password))

Chapter10_User/Projects/2024/Vano_Iniashvili/src/views/films/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField, DateField, FileField
from wtforms.validators import DataRequired


class UploadFilm(FlaskForm):
    title = StringField("Film Name", validators=[DataRequired()])
    director = StringField("Director")
    genre = StringField("Genre")
    release_date = DateField("Release Date")
    cover = FileField("Film Cover")
    submit = SubmitField("Upload")

Chapter10_User/Projects/2024/Vano_Iniashvili/src/views/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField

class EmptyForm(FlaskForm):
    button = SubmitField('Button')

Chapter10_User/Projects/2024/Vano_Iniashvili/src/__init__.py
from flask import Flask
from src.extensions import db, migrate, login_manager
from src.views.auth.routes import auth_bp
from src.views.films.routes import film_bp
from src.views.main.routes import main_bp
from src.config import Config
from src.commands import init_db
from src.models.user import User

BLUEPRINTS = [main_bp, film_bp, auth_bp]
COMMANDS = [init_db]


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    register_blueprints(app)
    register_extensions(app)
    register_commands(app)

    return app


def register_blueprints(app):
    for blueprint in BLUEPRINTS:
        app.register_blueprint(blueprint)


def register_extensions(app):
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(_id):
        return User.query.get(_id)


def register_commands(app):
    for command in COMMANDS:
        app.cli.add_command(command)

Chapter10_User/Projects/2024/Vano_Iniashvili/src/admin_views/__init__.py
from src.admin_views.base import SecureModelView, SecureAdminIndexView

Chapter10_User/Projects/2024/Vano_Iniashvili/src/views/__init__.py
from src.views.main.routes import main_bp
from src.views.films.routes import film_bp
from src.views.auth.routes import auth_bp

Chapter10_User/Projects/2024/Vano_Iniashvili/src/views/films/routes.py
from flask import Blueprint, render_template, redirect, url_for
from os import path
from uuid import uuid4
from flask_login import login_required, current_user

from src.extensions import db
from src.views.films.forms import UploadFilm
from src.views.main.forms import EmptyForm
from src.models.film import Film, UserFilm
from src.config import Config

TEMPLATES_FOLDER = path.join(Config.BASE_DIRECTORY, "templates", "films")
film_bp = Blueprint("films", __name__, template_folder=TEMPLATES_FOLDER)


@film_bp.route('/upload_film', methods=['GET', 'POST'])
def upload_film():
    form = UploadFilm()
    if form.validate_on_submit():
        cover = form.cover.data
        filename, file_extension = path.splitext(cover.filename)
        filename = str(uuid4())
        directory = path.join(Config.UPLOAD_PATH, f"{filename}{file_extension}")
        cover.save(directory)
        film = Film(title=form.title.data, director=form.director.data, genre=form.genre.data, release_date=form.release_date.data, cover=filename)
        db.session.add(film)
        db.session.commit()
    return render_template('upload_film.html', form=form)


@film_bp.route('/like_film/<int:id>', methods=['GET', 'POST'])
@login_required
def like_film(id):
    form = EmptyForm()
    if form.validate_on_submit():
        user_film = UserFilm(user_id=current_user.id, film_id=id)
        user_film.create()
    return redirect(url_for('main.home'))


@film_bp.route('/<user>/liked', methods=['GET', 'POST'])
@login_required
def liked_films(user):
    return render_template('liked_films.html')

Chapter10_User/Projects/2024/Vano_Iniashvili/src/views/main/routes.py
from flask import Blueprint, render_template
from os import path

from src.models.film import Film
from src.views.main.forms import EmptyForm
from src.config import Config

TEMPLATES_FOLDER = path.join(Config.BASE_DIRECTORY, "templates", "main")
main_bp = Blueprint("main", __name__, template_folder=TEMPLATES_FOLDER)


@main_bp.route('/')
@main_bp.route('/home')
def home():
    form = EmptyForm()
    films = Film.query.all()
    films_list = []
    for film in films:
        films_list.append(film)
    if form.validate_on_submit():
        ...
    return render_template('home.html', films=films_list, form=form)


@main_bp.route("/about")
def about():
    return render_template('about.html')

Chapter10_User/Projects/2024/Vano_Iniashvili/src/templates/films/liked_films.html
{% extends "layouts/base.html" %}

{% block title %}Liked Films{% endblock %}

{% block body %}
<div class="films">
    <div class="row">
        {% for film in liked %}
        <div class="col-md-3">
            <div class="mb-4">
                <img src="static/uploads/{{ film.cover }}.jpeg" class="cover">
                <div class="title-div">
                    <p class="title">{{ film.title }}</p>
                </div>
                <form action="{{ url_for('films.liked_films', user=current_user.name) }}" method="post">
                    {{ form.hidden_tag() }}
                    {{ form.button(class="btn btn-primary") }}
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Chapter10_User/Projects/2024/Vano_Iniashvili/src/templates/films/upload_film.html
{% extends "layouts/base.html" %}

{% block title %}Add Film{% endblock %}

{% block body %}
<div class="outer">
    <div class="middle">
        <div class="inner-upload-films">
            <form method="post" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.title.label(class="form-label") }}
                    {{ form.title(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.director.label(class="form-label") }}
                    {{ form.director(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.genre.label(class="form-label") }}
                    {{ form.genre(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.release_date.label(class="form-label") }}
                    {{ form.release_date(class="form-control") }}
                </div>
                <div class="mb-3">
                    {{ form.cover.label(class="form-label") }}
                    {{ form.cover(class="form-control") }}
                </div>
                {{ form.submit(class="btn btn-primary") }}
            </form>
        </div>
    </div>
</div>
{% endblock %}